### ISSUE TITLE
Oculus Medium will not start

### ISSUE THREAD

**Issue by marcoleone** [LibreVR/Revive#1074]
Oculus Medium won't start, I get a small window that says Error "Unable to initialize Oculus Rift" and after I click Ok I get another one - Fatal Error "Medium has crashed".
Any idea what could be the problem?

I also have Quill and it works fine.

Thank you!

**Comment by MatiasBrunacci** [comment]
Same here, It's happening with the Medium version 2.1
I had the same problem before with Medium version 2.0 and I solved it installing SteamVR Beta. But now it's not working again, even with SteamVR Beta installed.

**Comment by GlimArt** [comment]
I've been having the same issue. It started about three days ago, which seems to coincide with when Oculus's notifications tells me the software updated. Tried restarting, redoing and skipping set-up for the rift in the Oculus software, forcing a restart of Oculus in Settings>Beta, starting Revive via it's own .exe, starting Medium by dragging it's .exe onto Revive's. Everything short of reinstalling Revive. Might try that soon just to check it off the list but I doubt it'll help.

Hopefully we hear something soon. I was like 80% done sculpting VRChat avatars for some friends that're getting VR in a week. ;o;

**Comment by MatiasBrunacci** [comment]
> 
> 
> I am hitting the same thing. is there a way to downgrade medium until revive has updated?

I tried to find a way to downgrade but it seems to be not possible at all. 
(I should have turned auto-updates off when I could).

**Comment by sirkitree** [comment]
Seeing this as well. Turning off auto updates for oculus as this just keeps happening.

**Comment by siraxe** [comment]
same thing here with version 2.1 ( tried different revive versions , no luck so far

**Comment by Armada651** [comment]
No new Oculus SDK version has released, so I'd need to do some more research, fortunately I'll have internet at home again today so I can look at this in-depth.

**Comment by Armada651** [comment]
Found the issue, Oculus Medium is looking for some kind of old undocumented function that it doesn't actually use. Fixed in commit 69c4b2bcc416e45a4a9a24dccc02106e127bc158, will be fixed in the next release.

I'm currently setting up my Vive base stations, turnaround on fixes should be fast again.

**Comment by MatiasBrunacci** [comment]
> Found the issue, Oculus Medium is looking for some kind of old undocumented function that it doesn't actually use. Fixed in commit [69c4b2b](https://github.com/LibreVR/Revive/commit/69c4b2bcc416e45a4a9a24dccc02106e127bc158), will be fixed in the next release.
> 
> I'm currently setting up my Vive base stations, turnaround on fixes should be fast again.

Amazing! Thank you very much for all this effort guys! Much appreciated!

**Comment by GlimArt** [comment]
> 
> 
> Found the issue, Oculus Medium is looking for some kind of old undocumented function that it doesn't actually use. Fixed in commit [69c4b2b](https://github.com/LibreVR/Revive/commit/69c4b2bcc416e45a4a9a24dccc02106e127bc158), will be fixed in the next release.
> 
> I'm currently setting up my Vive base stations, turnaround on fixes should be fast again.

Aww yiisss. Been checking this thread every day. Thank you so much!

**Comment by Armada651** [comment]
Working on one more input bug (thumbstick suddenly snapping to the forward position) before I release the fixed version.

**Comment by Armada651** [comment]
Oculus release version 1.30 of the SDK yesterday which includes the header and documentation for the function that Oculus Medium required. So it looks like the Oculus Medium update was compiled against an unreleased version of the Oculus SDK.

Now I can properly implement the function and release a new version.

**Comment by sirkitree** [comment]
Sweet! Looking forward to it!

/me preps his pumpkin carving skills https://forums.oculusvr.com/community/discussion/69929/annual-pumpkin-sculpting-contest ;)

**Comment by Armada651** [comment]
Fixed in the latest release: https://github.com/LibreVR/Revive/releases/latest

**Comment by alanboucek** [comment]
this fix works for me- awesome! also, I can confirm that it works with Quill

**Comment by siraxe** [comment]
It works again , thank you so much )

**Comment by ryansullivanuk** [comment]
I'm still facing this issue.... Tried steamVr in every build (betas and openvr input emulator(which wont even load steam vr at all)). Ive tried various builds of revive too, really stuck here, any help would be greatly appreciated. (Ps I'm using WMR dell visor).

Thanks again

**Comment by jak2030** [comment]
👋 I'm experiencing the exact same pattern as @miscmouse 


Revive 1.6.2
Medium 2.2.1
SteamVR Beta 1.2.9 and SteamVR 1.2.7
Vive Pro

**Comment by jak2030** [comment]
@miscmouse Got it - that describes my situation then. Thanks for letting me know!

**Comment by miscmouse** [comment]
@jak2030 Confirmed working now with newest revive release, for me at least. Give it a shot!
