### ISSUE TITLE
Dance Central crash on Start-Up

### ISSUE THREAD

**Issue by LightbeamZ** [LibreVR/Revive#1334]
**Describe the bug**
_A clear and concise description of what the bug is._

The game **Dance Central** is not starting properly and crashes with a black screen. One starting issue of the game was fixed with Revive 1.7.3 and that version of Revive is still working now. But Revive versions after 1.7.3 broke it again, so 1.8.1 is not working and people in the old issue thread reported that 1.8.0 is also broken. (https://github.com/LibreVR/Revive/issues/1221) 

**To Reproduce**
_Steps to reproduce the behavior:_

1. Launch Dance Central with Revive
2. Game will show Dance Central Logo and freeze with Black Screen

**Expected behavior**

The game should just start.

**Environment (please complete the following information):**

 - **App: Dance Central**
 - CPU: AMD Ryzen 7 3700x
 - GPU: AMD RX Vega 64 LC
 - RAM: 16GB DDR4 3600MHz
 - OS: Windows 10 Pro 1903 [Build 18362.356]
 - Headset: Vive with TPCast (Open TPCast)

**Versions (please complete the following information):**

 - Revive: 1.8.1
 - SteamVR: 1.7.15

**Additional context**

It would be nice if this get fixed because its pretty bad to deinstall/reinstall different versions of revive to get different games working.

**Comment by deinlandel** [comment]
Can confirm Dance Central crash on latest release

**Comment by Armada651** [comment]
Fixed in the new release: https://github.com/LibreVR/Revive/releases/tag/1.8.2

**Comment by dashrava** [comment]
Not getting a crash on latest Revive+SteamVR on Index, but the game window says:

"You have a pending hardware issue that is preventing you from entering VR. Please check that your headset and sensor are connected."

Nothing appears in HMD.

**Comment by haywirephoenix** [comment]
this is still happening :(

**Comment by LightbeamZ** [comment]
I just played it with the current version of Revive 1.9.2.0 on HTC Vive and its working fine. So whatever problem you have its probably not one with Revive.

**Comment by ClarkHH** [comment]
This is still happening for Revive 1.9.2.0

![image](https://user-images.githubusercontent.com/60045407/72669293-33325800-3a30-11ea-8fd2-a581368ae1fc.png)

**Comment by Bobcorn008** [comment]
@LightbeamZ Hi I'm wondering if you started the game, and Dance Central LOGO showed, but nothing happened but black background, with only a purple footprint on the floor? How did you fix this? I've used 1.73, 1.82, and latest version of Revive, still got this bug.

**Comment by LightbeamZ** [comment]
I don't have my VR setup on hand right now to try it again. But as far as I remember every version of Revive after 1.8.2 and also the latest 2.0.0 release worked for me. It boots up with the big Dance Central logo and drops you into the game. If the game still crashes for you at the Dance Central logo you should try do uninstall Revive completely and also delete all old files of it. Then reinstall the newest version of Revive 2.0.0 and try again. If this does not help maybe Dance Central got an update that make the game crash again or its something completely different and / or specific to your system / VR setup.
