### ISSUE TITLE
Anyone tried Edge of Nowhere with Revive yet?

### ISSUE THREAD

**Issue by iamwes** [LibreVR/Revive#138]
I know its just come out, but was wondering if anyone has tried Edge of Nowhere with Revive yet? This is one i definitely want to buy if its confirmed to work? I'm currently running the v1.3 downgrade.

Any news would be great, thank you.

**Comment by SchmockLord** [comment]
I've tried it. Its not working. Same as with Adr1ft: The Logo appears shortly and then the following error message appears: "A connection to the Oculus Store could not be established. Please check your internet connection and firewall and make sure that you are logged into your Oculus Store account."

I'm a Vive-only owner but I have a friend who owns the DK2. I might ask him if he can borrow me the DK2 so I can atleast play Edge of nowhere somehow.

**Comment by SchmockLord** [comment]
Update: Have to revise myself. After downgrading my Oculus Runtime to 1.3 it is working with Revive 0.6!!!

**Comment by SchmockLord** [comment]
Holy shit, this is intense. This game is awesome. Worth every penny so far.

**Comment by iamwes** [comment]
Great news! Thank you for the update, I'm running 1.3 atm so will get it soon.  Can't wait looks good!

**Comment by xeno3d** [comment]
Id love to try this on my Vive.  So far Revive is working great but it seems that without Oculus 1.3 I can't run Edge of Nowhere.  How can I get Oculus 1.3?  All I have is 1.4

**Comment by avspap** [comment]
I would also like instructions for this.

**Comment by f00d4tehg0dz** [comment]
xeno3d you can use this to revert back. https://www.reddit.com/r/Vive/comments/4kd08m/revive_compatible_oculus_runtime_132_is_still_on

Anyone having a lot of flickering in the game?

**Comment by godwisper** [comment]
tried with 1.3.2 oculus and revive 6 and still get same error to connect to oculus home

**Comment by Ozone72** [comment]
I've downgraded also, and have ReVive 5.2.  I also get the "can't connect" error.  It has to be firewall related.  Is my best guess.   In my case, this is a 'The Climb' issue.  Basically, same problem.  There is an in/out issue.  There are a few previous posts that relate to which .exe/services are getting through, but nothing *very soecific*.  I'll keep messing around :)

**Comment by godwisper** [comment]
I tried with both revive 0.6 and 0.5.2 injector and not and get same. Let me know if you find anything

**Comment by godwisper** [comment]
ok think I got it to work. You need to remove the block on the outbound rules in firewall and leave blocked the inbound

**Comment by Ozone72** [comment]
I had it reversed.  Thank you!

**Comment by godwisper** [comment]
looks ugly as game lol...so far not worth it...yucks like a 2D

**Comment by iamwes** [comment]
Really? It got really good reviews... hm

**Comment by SchmockLord** [comment]
My procedere is the following:

0. Install current Oculus Runtime.
1. Download and Install (also "Finish Installation") all the Oculus Games you wanna play until every game shows you the "Start" button.
2. Quit Oculus.
3. ForceQuit the Oculus background programs in the task manager. This should also stop the Oculus runtime service. If not, you have to to stop it manually. Otherwise you won't be able to replace the runtime files with the 1.3 files.
4. Go into the Oculus root folder and delete the "swap"-folder.
5. Replace all the contents of the Oculus root folder with the ones from the 1.3 installation.
6. Start the Oculus runtime service again.
7. Run SteamVR.
8. Make sure the Oculus exe-files aren't blocked, otherwise you will receive the error message that the game can't connect to the oculus store.
9. Either start "Edge of nowhere" with the injector or open SteamVR, go to the Revive Dashboard and start it from there.

Beside that procedure I've created inbound and outbound blocking rules for every Oculus related exe in the Oculus service folder. This way I can enable/disable blocking flexible.

But so far I didn't find any suitable combination of the blocking rules that enable playing games but keeping the the Oculus runtime from connecting home and downloading the newest 1.4x runtime.

Thats why I have to redo the procedure for every game session so far.

I would appreciate if someone could tell me how to setup the firewall rules to prevent the runtime service from dowloading the newest runtime.

I think there is something to do with the swap folder that is created by the runtime everytime it's detecting an older runtime.

It seems, that oculus downloads all the new runtime files in the "swap" folder and uses them instead. Maybe I just have to setup rules for the exe-files in the swap folder.

**Comment by f00d4tehg0dz** [comment]
So no-one else has artifact issues like I'm having?

**Comment by LorkHang** [comment]
Before 1.4 release, I stopped the OVRLibraryService from OS startup and blocked OculusClient.exe and OculusVR.exe(outbound only), it never upgrades to 1.4.

Now I can still run chronos and the climb(OVRserverx64 or OVRServiceLauncher need to be unblocked to run this one) with revive 0.5, not yet tried EoN though.

**Comment by LorkHang** [comment]
@f00d4tehg0dz I don't own this game but did you uncheck game threatre with steamvr?

**Comment by LibreVR** [comment]
@f00d4tehg0dz Flickering is a performance problem, what are your system specs and what method are you using to start the game?

**Comment by godwisper** [comment]
yes I noticed artifacts especially in the beginning on the snowy landscape

**Comment by iamwes** [comment]
Artifacting usually only occurs if your GPU is getting too hot, or overclocked too much. Maybe try a fresh reinstall of the graphics driver... if not try turn the graphics / resolution down a bit.

**Comment by f00d4tehg0dz** [comment]
@godwisper you did too? Ok thats the EXACT issue I'm mentioning. Its a strange artifacts around the snow landscape near the pirate ship.

My GPU isn't overheating (thankfully) 980TI, I7 4790K liquid cooled. Godwisper mentioned the exact artifcating that I faced too.   I'll try uncheching game theater in steam vr @LorkHang  thanks!

**Comment by LibreVR** [comment]
@f00d4tehg0dz Oh that's definitely not a performance problem, I'll look into it. Seems to be a layering issue, I'll try to fix it in the next version.

**Comment by f00d4tehg0dz** [comment]
@LibreVR thank you very much!

**Comment by EternalGamer** [comment]
So I bought this game impulse when it came out yesterday blindly (and stupidly) assuming I could get it to work with Revive after having great luck with Chronos but I've had nothing but headaches trying to get it working.

I just got my Vive last week so I don't have access to Occulus 1.3 and all the guides i've used and followed to a T just end up in Occulus breaking and giving me Runtime errors causing me to have to redownload the whole program again to fix it.

Schmidlock Lord's solution looks good and easy to follow (I've messed around with those files so much I know them on sight and location by hand), but the problem is I don't currently have the 1.3 files to downgrade to and using that patcher program to downgrade the runtime library doesn't seem to do the trick.  When I paste it back into the Occulus Runtime folder that's always when Occulus Home stops working and gives me an error.

**Comment by Trelas** [comment]
I have also downgrade the runtime to 1.3 and can play "Luckys Tale" and Chronos. 
But can´t play Edge of Nowhere:  "A connection to the Oculus Store could not be established.".
(Oculus is blocked in the Firewall)
Testet with all version of ReVive from 0.5 to 0.6.

**Comment by iamwes** [comment]
You need to unblock it in the firewall to play  EON

**Comment by Trelas** [comment]
@iamwes
OK have unblocked Oculus Home (and can see the store) in the firewall, this also don´t work.

**Comment by iamwes** [comment]
You need everything unblocked in the firewall. And the newest version of revive... should work

**Comment by iamwes** [comment]
Maybe try restarting oculus properly

**Comment by EternalGamer** [comment]
How did you guys do the revert to 1.3?  Did that runtime patcher work for you?  For me it just breaks Occulus and I have to reinstall the 800MB download everytime (no small amount of time since I'm on a slower DSL connection).

**Comment by Trelas** [comment]
@EternalGamer

**Comment by Trelas** [comment]
@EternalGamer
i use the runtime patcher and become no error.
@iamwes
No Oculus exe is now blocked, but the message is the same.
:-(

**Comment by Trelas** [comment]
For what are the Manifests in te Oculus folder?
insomniac-games-edge-of-nowhere.json
"firewallExceptionsRequired": true

insomniac-games-edge-of-nowhere_assets.json
"firewallExceptionsRequired": false

I have change this to "false" with no effect.

**Comment by Trelas** [comment]
I have temporary disable my Firewall and all is OK.
It´s not so easy to become this work with AVG Internet Security!

**Comment by avspap** [comment]
I have runtime 1.2 installed from the revive page. Should I uninstall that and install from the oculus site and then replace with the downgrade patch?

**Comment by Ozone72** [comment]
To confirm, as soon as I reversed the in/out rules 'The Climb' fired right
up!
On Jun 6, 2016 11:45 PM, "godwisper" <notifications@github.com> wrote:

ok think I got it to work. You need to remove the block on the outbound
rules in firewall and leave blocked the inbound

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LibreVR/Revive/issues/138#issuecomment-224194310>, or mute
the thread
<https://github.com/notifications/unsubscribe/ALHTl6sOGLGDmRAFBksv-QMV8yZHF_Fbks5qJRN9gaJpZM4IurxY>
.

**Comment by Ozone72** [comment]
It's ok, but as one of the more highly rated games on the Oculus platform,
I'm a little surprised.   With Touch support, it would be much much
better.

**Comment by iamwes** [comment]
Im going to buy it when i get home from work, will let people know what i think of it tonight

**Comment by iamwes** [comment]
Downloading it now, whilst im waiting i was playing around with the Revive patch and managed to get Adr1ft working, if anyone is interested i posted the instructions here: http://steamcommunity.com/app/300060/discussions/0/350533172680477831/

**Comment by iamwes** [comment]
Got edge of nowhere working, same issue with me the graphicsame break up a bit mainly in white areas, I'm running 2x 980Ti SLI so it's not that. Maybe you can patch it. Otherwise runs great and started out pretty weird I like it.

**Comment by Brody79** [comment]
If you want to prevent Oculus to upgrade the Oculus drivers you have to revoke the full and modify permissions of the Oculus folder (or the support subfolder at least).

**Comment by iamwes** [comment]
Thats interesting how do you do that? So far mines been ok, i unblock the firewall, start the game then just block it again when the menu screen loads up (game still plays fine).

**Comment by Brody79** [comment]
Just edit the permissions on the folder: right-click it, click on properties, select the security tab and click on edit. Select the OVRLibrary user and uncheck full control and modify, done.

**Comment by noisyboyuk** [comment]
I literally just managed to get it working (this is my first attempt at playing Rift games on Vive). Does anyone know why my controller might not be working? I have a steam controller set to an X-Box 360 profile but can't get passed the first screen (which asks you to press A). So I tried to turn on and press all of the buttons of my Vive controllers but again nothing and finally I tried literally pressing every key on my keyboard and mouse but alas still no joy. I'm sure it's something I have missed but any ideas would be welcome! Thanks!

**Comment by iamwes** [comment]
I'm afraid I've never used a steam controller, I'm using a wireless xbox one controller and it works fine with the game, I don't see why it wouldn't work though.  Have you tried using it not set to an xbox 360 pad and just a steam controller?

**Comment by noisyboyuk** [comment]
I'll give that a shot and see what happens! Thanks!

**Comment by noisyboyuk** [comment]
Still no joy. Tried all the game pad modes but still nothing. If anyone else has used something other than an X-Box controller I'd love to hear if you had any issues.

**Comment by LibreVR** [comment]
The new Oculus Runtime removed the headset check from the DRM. You can now play Denuvo games without downgrading.

**Comment by cccpphil** [comment]
The game works with 0.6.2

**Comment by Deepo** [comment]
Is the flickering issue fixed in 0.7?

**Comment by iamwes** [comment]
Still the same... its not too bad though

**Comment by LibreVR** [comment]
I'm currently testing a fix that solves a similar flickering in the loading screen of Farlands. It'll be part of version 0.8, hopefully it will also solve the flickering problem in Edge of Nowhere.

**Comment by LibreVR** [comment]
Please test the latest release, it may fix the flickering issue.

**Comment by f00d4tehg0dz** [comment]
Issue still persists. Although it seems to be less harsh. 

I did a full reinstall of oculus home (latest version), revive (latest) and downloaded edge of nowhere.

**Comment by LibreVR** [comment]
Thanks for the feedback, I will make sure that it's fixed in the next release.

**Comment by Gruguir** [comment]
It still has flickering/artefacts issues for me with the latest version of Revive. Also it seems to be really aliased (looks like MSAA is not activated at all), but maybe it is just the game and not an issue. Overall the game is playable :) (and awesome)
