### ISSUE TITLE
Golf+ doesn't launch correctly in headset

### ISSUE THREAD

**Issue by Pottypotsworth** [LibreVR/Revive#1804]
**Do not report issues when using the Virtual Desktop or ALVR drivers for SteamVR, this is not supported by Revive.**

**Describe the bug**
When opening Golf+ from the revive menu, the application launches in the background in Windows but does not launch on on the Valve Index HMD. The sound comes through the HMD ear speakers, but there is no visual. Controller input is also not detected on the app that has loaded in Windows.

**To Reproduce**
1. Go to Revive inside Steam VR
2. Click on Golf+
3. Issue happens as above.

**Expected behavior**
Golf+ should launch correctly inside the HMD and allow you to play.

**Environment (please complete the following information):**
 - App: Golf+
 - OS: Windows 10
 - Headset: Valve Index

**Versions (please complete the following information):**
 - Revive: 2.1.1
 - SteamVR: 1.24.7

**Additional context**
Apparently Golf+ worked for a long time, but broke around the 10th Jan 2023 due to a developer update "to comply with new Meta backend changes"

**Comment by RyDon26** [comment]
I am also experiencing this issue. I have tried updating SteamVR to beta then reverting and that seemed to not be effective either.

**Comment by jay22deuce** [comment]
Same here.  Using wmr and revive.

**Comment by CrossVR** [comment]
> Apparently Golf+ worked for a long time, but broke around the 10th Jan 2023 due to a developer update "to comply with new Meta backend changes"

This probably means they updated to the latest OVR SDK, try the new release: https://github.com/LibreVR/Revive/releases/tag/3.1.1

**Comment by Pottypotsworth** [comment]
> This probably means they updated to the latest OVR SDK, try the new release: https://github.com/LibreVR/Revive/releases/tag/3.1.1

Hey, thanks for the heads up. Unfortunately the issue doesn't seem to have been fixed :(

**Comment by RyDon26** [comment]
And Golf+ released an update as well. Darn shame. When it works it is one of the better games out there...

**Comment by CrossVR** [comment]
Can you try this beta version when it finishes building?

https://ci.appveyor.com/project/LibreVR/revive/builds/46502368/artifacts

**Comment by Pottypotsworth** [comment]
> Can you try this beta version when it finishes building?
> 
> https://ci.appveyor.com/project/LibreVR/revive/builds/46502368/artifacts

You absolute legend 👍 Golf+ is working perfectly with this build, well done 👏

**Comment by xxTheGoDxx** [comment]
Still doesn't work for me, even with the 3.1.1.85 version posted here (or any newer for that matter). Opens up intro video, continues to the loading screen and then the game exists. Valve Index, Win 11.

**Comment by CrossVR** [comment]
Try this new release: https://github.com/LibreVR/Revive/releases/tag/3.2.0

**Comment by xxTheGoDxx** [comment]
And it turns out it was something on my end. While reinstalling the game didn't help, reinstalling both the game and the Oculus Home software fixed the problem completely. Thanks a lot.
