### ISSUE TITLE
Model Rotation in Medium

### ISSUE THREAD

**Issue by jtryon** [LibreVR/Revive#431]
When using the grip to rotate a model in Medium upon passing about 60degrees or more of rotation the model whips around violently.

This doesn't appear to be related to tracking.  Observing the controller model it remains smooth and stationary while the model in Medium is whipping around.

I think it's probably related to revive but can't confirm as I have no access to an Oculus setup.

If necessary I can probably record a video of it happening as it's kind of hard to describe..  Hope someone else can confirm.

**Comment by RocketBun** [comment]
I can confirm this is happening as well. It's really odd, sometimes the world just sort of.... flips around. Exremely annoying, and definitely not related to my controller tracking.

**Comment by Armada651** [comment]
There is a known jitter issue that I'm still working on fixing. I'll also see if I can reproduce the rotation issue.

I can probably work on this on Monday.

**Comment by Armada651** [comment]
I can't reproduce the problem unfortunately.

**Comment by jtryon** [comment]
I'll create a video later tonight showing the exact issue (assuming I remember).  Hopefully that can help.
The nature of how it snap-flips 180 degrees at an exact point of rotation every time makes me think it is some kinda bug.

Also, if it's relevant this is on the Nvidia 1070.

**Comment by Armada651** [comment]
Can you reproduce it with every sculpt?

**Comment by jtryon** [comment]
I can.  I did a fresh sculpt here just to demonstration, tried to keep it short:
https://www.youtube.com/watch?v=b_nLCW5QMYI

Note: those "errors" popping up on my tool hand are related to screenshots I've deleted since closing Medium last time.  It just gripes that they're no longer where it left them.  Unrelated.

**Comment by makerboost** [comment]
I get the same error, but every time I use one hand to rotate the model and it flips out, I can switch to the other hand. This works fine for a while until it starts flipping out, but then I switch back to the first hand. After a while, it seems like the error accumulates, and it becomes harder and harder to move the objects around without making them spin.

**Comment by chemb0t** [comment]
I am seeing similar behavior in Quill as well as medium. When using both hands to move or scale, the model would occasionally flip 180 or 90 degrees. Could it have something to do with the way it's calculating pose/vectors when both hands are being used? I'm not seeing these issues when using one hand for moving.

**Comment by jtryon** [comment]
I see the issue at specific rotation point and when using only a single hand to grip.  In the video posted above I am rotating with a single grip button held.

**Comment by makerboost** [comment]
I made a sculpture and saved it when it started behaving weird. Problem persists after restarting Medium, and reloading the file. 
Download here: https://drive.google.com/file/d/0B-qY04DzmKsebDRrYmF2TDBCMUk/view?usp=sharing

It seems like there's a rounding error with rotation. Example; if you grab the object, and rotate your hand 0 - 361 degrees. Instead of looking like a seamless rotation, the model "lerps" from 0 to 360 the opposite way/rotation until it reaches the correct value, and then continues like normal to 361.

**Comment by Urthiel** [comment]
I have an exact same issue. While rotating model it sometimes starts jumping and flipping and moving uncontrollably, to an extend that afterwards it is sometimes hard to find it and get back to desired position. I would love to see that fixed as you really can't work effectively this way.

**Comment by k1down** [comment]
Still experiencing this issue. It seems to happen at certain degree points of rotation as if it's crossing some threshold and then doing some bad math for a second and flipping out, then getting it back together and having the model as it should be again. Left-handed one-handed grip rotation is the easiest way to reproduce the problem in my experiences.

**Comment by jtryon** [comment]
Can confirm, still seeing the issue.

**Comment by Armada651** [comment]
I'll be on a much needed vacation next week, but once I'm back I plan to devote a lot more time to fixing Revive issues again.

**Comment by jtryon** [comment]
Not sure if this is still on your plate or not.  Just thought I'd mention I'm still interested in a fix.

**Comment by Armada651** [comment]
This is a bit more difficult than fixing a few tracking latency and controller detection issues. But I'll attach a milestone to make sure I won't forget about it in the next large release.

**Comment by Armada651** [comment]
I haven't been able to reproduce this in time for the 1.1 release.

How large does your model need to be before this starts happening?

**Comment by jtryon** [comment]
I updated revive and medium to the latest versions and tested fresh.
On a new project file with the tiniest model I could think to make (just a quick single stroke of the basic brush tool).  Rotating it in the fashion shown in the video before (and posted again here) still does the flippy thing.

Seems like an issue reporting the rotation of the controller or something.  Note it always happens at the same relative point of rotation.

Previous video:
https://www.youtube.com/watch?v=b_nLCW5QMYI

**Comment by Armada651** [comment]
I see, it's probably a continuity problem in the angle, that's probably the point where -180 changes to 180.

**Comment by Armada651** [comment]
Okay I was able to reproduce it, the cause seems to be the x and y axes of the quaternion swapping the sign (positive/negative) at that exact angle.

**Comment by Armada651** [comment]
Fixed in commit 1655efedd418f6da2e01322069aa466868d6d5cb.

**Comment by Armada651** [comment]
New version is released: https://github.com/LibreVR/Revive/releases/tag/1.1.1

**Comment by goshwinkle** [comment]
Just tested, Is still flipping around for me. Checked and revive version shows as 1.1.1. Not sure if I've messed anything else up

**Comment by goshwinkle** [comment]
just quit steam and revive and steamvr and reopened. still happening

**Comment by Armada651** [comment]
Damn, this is so hard to reproduce, but it shouldn't hapen as often at least. I'll see if I can improve the detection of when the angle flipped.

**Comment by Armada651** [comment]
Hotfixed in commit 94dda1f0ffc20a7f311d11c8be86d1a727e4f77a.

For real this time. I replaced the original 1.1.1 release, so just re-download it or use the update checker.

**Comment by Armada651** [comment]
For people who like quaternion math (do those people exist?). I corrected the angle of the rotation not flipping, but I didn't account for the fact that the axis could also flip and still represent the same rotation.

**Comment by Nontouchable** [comment]
you sir are amazing! I was just about to comment, that I have been using medium for 3 hours straight now, with no flipping. Then it suddently happened, it seemed to have to do with either the time passed or the sculpt size. I then saved, reopened the same, it persisted. Saved, opened new, it persisted.
Restarted the complete steamvr, revive overlay etc., opened the same sculpt, no problem for about 30 minutes.
Now I see you found the culprit, I'll be sure to test this and let u know.

**Comment by goshwinkle** [comment]
Fantastic! it works. So nice to be confident when moving the sculpture. Thank you so much for your work!

**Comment by Armada651** [comment]
In the end I decided to keep relying on the previous orientation and use that data to also calculate the missing acceleration values that were not implemented yet.

So there won't be any more changes to this fix, you can see the final result in commit 1eaeda61cfb61869af47a785aa54b2b87134805a.
