### ISSUE TITLE
Lots of games no longer working with Oculus and Revive updates

### ISSUE THREAD

**Issue by jfb4497** [LibreVR/Revive#569]
Hi, 

I am noticing that a lot of (mostly unreal based) games are either unstable or no longer work. I hadn't touched many of the older apps today until I was messing around. A lot of them seem to crash now. I've tried running both steam and revive in adminstrator mode to see if that would help, but it does not appear to do so. Examples of the games and experiences that crash (either with injecting or through the dasboard):

Introduction to VR
Showdown
Lucky's Tale
Farlands
Ripcoil
Lost

Games that still seem to work:
Chronos
Bullet Train Demo
Henry
Dreamdeck

This is with release version https://github.com/LibreVR/Revive/releases/tag/1.1 and Oculus 1.13 runtime. I tried a lot of the recommendations found in issue #557, but nothing seems to be working.

**Comment by Armada651** [comment]
Thanks for reporting, I've messed up a version check, luckily I can release a hotfix right now.

**Comment by Armada651** [comment]
Should be fixed now, just redownload version 1.1 or run the update checker.

**Comment by jfb4497** [comment]
I'll try it out. If there are logs or anything that you could point me towards, I could also post those.

**Comment by Armada651** [comment]
@jfb4497 Can you confirm the new hotfix works? I'd like to go to bed soon. ;)

**Comment by jfb4497** [comment]
Hmm, Lucky's Tale is still crashing even with the update.  However, Introduction to VR and Ripcoil now work again. Farlands seems to sometimes work but is very prone to crashing.

**Comment by jfb4497** [comment]
Don't stay up too late on account of me. This can wait until you are more rested. Your work is very much appreciated!

**Comment by Armada651** [comment]
@jfb4497 I can't reproduce the crash anymore with the hotfix, are you sure you're running the right version? You can double-check it by right-clicking the Revive tray icon and clicking "Check for updates". It should tell you that you're running version 1.1.0.1.

**Comment by jfb4497** [comment]
Yep, I'm running that version. It could be something on my end, however. Other applications that weren't working do appear to be working again. I may try uninstalling and reinstalling some of the applications that are still acting up.

**Comment by Armada651** [comment]
Well, let's limit ourselves to Lucky's Tale, it doesn't crash for me anymore. Does it still crash for you?

**Comment by jfb4497** [comment]
Oh hey, I had tried patching it earlier. Deleting the patch files from the Lucky's Tale folder has led it to working again. I'll make sure I don't have old injector files or patch files in the other app folders. That will have to wait until a little later though as I am heading out for food. :) 

Thanks again!

**Comment by Armada651** [comment]
Never use the patching functionality on an Oculus Store game. Patching it copies the current version of Revive into the game folder, which won't be automatically updated.

**Comment by jfb4497** [comment]
So Showdown and Ghost in the Shell remain the only two experiences that still don't work with the new update (even after uninstalling and reinstalling). Everything else appears to be working much better. Thank you!

**Comment by Krylke** [comment]
Edge of tomorrow still has flickering issues on some textures but its much better than it was and it runs much better too. It appears it has something to do with snow or ice because in the later parts of the game without snow there is no flickering at all now. I have the latest patch and hotfix installed.

Great job and thank u so much for making revive. I really love the software :-)

**Comment by Armada651** [comment]
The flickering issues is known and affects The Unspoken too because it uses the same engine, though it is affected to a lesser degree. I have not yet found the cause because all the tools I normally use to debug such issues crash when used on Edge of Nowhere.

**Comment by Armada651** [comment]
@jfb4497 Showdown is working for me, you either patched it with the broken version of you are not starting it through the Revive Dashboard.

I can reproduce the Ghost in the Shell crash, but it doesn't seem to be related and it crashes on version 1.0.6 also. You can submit a new ticket for that issue.

**Comment by Armada651** [comment]
On closer inspection, it is related. I didn't notice that the struct returned by `ovr_GetPerfStats()` was expanded with new ASW variables. This causes Revive to write outside of the bounds of the buffer quickly crashing the application.

**Comment by Armada651** [comment]
New version is released: https://github.com/LibreVR/Revive/releases/tag/1.1.1
