### ISSUE TITLE
Medium Experiencing some Jittering in the most random moments

### ISSUE THREAD

**Issue by shadypotato** [LibreVR/Revive#725]
When I first opened Medium On Revive, Everything was Jittery. So I had Exited Revive, and Started Back up; which I thought would solve the problem. Then I noticed Whenever I played a tutorial - or sculpted really large objects the Environment Would Jitter again. Is there anyone else experiencing this Phenomenon?

**Comment by Theoneonlykid** [comment]
yep right there with you posted the same question about 5 days ago has your cpu usage been through the roof as well??

**Comment by Cless-Aurion** [comment]
Yep, Medium is completely broken for me since like... the last big Medium update (around June). Very jittery, worse than in the past.
Disabling asyncronous reprojection and Interleaved reprojection doesn't help like it used to to.
Going to any older working version of Revive makes the game not boot at all either, so that's out of the question to...
Anyone has found a workaround?

**Comment by Cless-Aurion** [comment]
So... I'm posting again because I seem to have kind of "solved" it.
I've read in old posts here to run steam as an admin. After doing that and it got better.
But then, all the problems on April reapeared. Having to turn off interleaved reprojection and asyncronous reprojection helps, but sculpting high poly sculpts can be pretty anoying because of the jitter.

**Comment by Armada651** [comment]
Have you tried switching to the SteamVR beta with Asynchronous Reprojection **on** yet?

**Comment by Cless-Aurion** [comment]
Yes I did. And it fixes the jittering, but it makes it worse, it runs at what it feels 20-30fps.
(I got a i7-6700 and a GTX 1070, so that shouldn't be an issue)

**Comment by Balderick** [comment]
30 fps is indicative debug mode is active with extended display.   Spend time making direct mode work.

**Comment by Cless-Aurion** [comment]
Well, I haven't changed it, it's still in Direct mode. I double checked. Not in extended mode as far as I'm aware.

**Comment by Armada651** [comment]
@chrisbraeuer411 Can you try extracting this into your Revive installation folder, replacing the existing files: 
[Revive.zip](https://github.com/LibreVR/Revive/files/1238808/Revive.zip)

This completely disables haptics, so if the performance problem is related to the rumble then this should fix it.

**Comment by Armada651** [comment]
@chrisbraeuer411 Remember to report whether that build fixes the problem.

**Comment by chrisbraeuer411** [comment]
Okay you Haptics disable patch made the rumble stop.
But the performance problems are still there.
To wrap it up:
If you just boot it up and play around a bit it works. But as soon as you go bigger the problems start. That is the case for medium since release and never changed. Just load up the robot shop or the mech for example and you see what i mean. If you go close you get like 10fps. It cant be my system ( 1080gtx, i7, 16ram).
I also tried with and without steamvr reprojektion/ asyncreprojektion, but there in no difference at all.
SteamVR beta/win10

**Comment by Armada651** [comment]
I'm working on a lot of performance improvements and in my development version Oculus Medium has already improved. I will continue to refine the performance of Revive and hopefully that'll fix Oculus Medium once and for all.

**Comment by Cless-Aurion** [comment]
@Armada651 Amazing! Medium is such an amazing tool.
Thanks for all your hard work! =)

**Comment by chrisbraeuer411** [comment]
Sounds great. Thanks for looking into it. Its really an awesome tool.

**Comment by Armada651** [comment]
Please test this beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0

**Comment by Cless-Aurion** [comment]
It didn't work for me. I opened a new issue with the error I got here:
https://github.com/LibreVR/Revive/issues/755

**Comment by Cless-Aurion** [comment]
Ok, once fixed that issue, Medium works buttery smooth. It is still there, but its so uncommon I feel it could be a Medium issue instead of Revive.
I would say its fixed for me. Amazing work Armada651! Thank you so much!

**Comment by Armada651** [comment]
That's great news, make sure to turn Asynchronous Reprojection on to take care of those final few jitters.
